"""
RAG chain orchestration.

Connects the retrieval results to the LLM via prompt templates.
Supports both streaming (for live UI) and non-streaming (for testing).

Key design choice: context is pre-built from retrieved docs and
injected directly into the prompt — this eliminates the "double
retrieval" bug where displayed sources could differ from the
context the LLM actually used.
"""

from langchain_core.documents import Document
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)

from core.llm import get_llm
from core.prompts import RAG_SYSTEM_PROMPT, RAG_USER_TEMPLATE
from utils.logger import setup_logger

logger = setup_logger("nexus.rag")


# ──────────────────────────────────────────────────────────────
#  FORMATTING HELPERS
# ──────────────────────────────────────────────────────────────

def format_context(docs: list[Document]) -> str:
    """Format retrieved documents into a labelled context string.

    Each chunk is tagged with its source and type so the LLM can
    attribute information in its answer.
    """
    sections = []
    for i, doc in enumerate(docs, 1):
        source = doc.metadata.get("source", "Unknown")
        doc_type = doc.metadata.get("type", "unknown")
        page = doc.metadata.get("page", "")
        page_str = f", p.{page}" if page else ""

        sections.append(
            f"[Chunk {i} | {source}{page_str} | {doc_type}]\n"
            f"{doc.page_content}"
        )
    return "\n\n---\n\n".join(sections)


def format_chat_history(
    history: list[dict], max_turns: int = 5
) -> str:
    """Format recent chat turns for inclusion in the prompt.

    Only the last ``max_turns`` are included to stay within context
    window limits.  Answers are truncated to 500 characters.
    """
    if not history:
        return "No prior conversation."

    recent = history[-max_turns:]
    lines = []
    for turn in recent:
        lines.append(f"User: {turn['question']}")
        answer_preview = turn["answer"][:500]
        lines.append(f"Assistant: {answer_preview}")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────
#  CHAIN CONSTRUCTION
# ──────────────────────────────────────────────────────────────

def _build_chain():
    """Construct the prompt → LLM → parser chain.

    Uses a system message for the AI persona and rules, and a
    human message template for the context + question.
    """
    prompt = ChatPromptTemplate.from_messages(
        [
            SystemMessagePromptTemplate.from_template(RAG_SYSTEM_PROMPT),
            HumanMessagePromptTemplate.from_template(RAG_USER_TEMPLATE),
        ]
    )
    llm = get_llm()
    return prompt | llm | StrOutputParser()


# ──────────────────────────────────────────────────────────────
#  PUBLIC API
# ──────────────────────────────────────────────────────────────

def generate_answer(
    query: str,
    retrieved_docs: list[Document],
    chat_history: list[dict],
) -> str:
    """Generate a complete answer (non-streaming).

    Use this in testing or when streaming is not needed.

    Args:
        query: The user's question.
        retrieved_docs: Documents returned by the retriever.
        chat_history: Previous conversation turns.

    Returns:
        The full answer as a string.
    """
    chain = _build_chain()
    answer = chain.invoke(
        {
            "context": format_context(retrieved_docs),
            "question": query,
            "chat_history": format_chat_history(chat_history),
        }
    )
    logger.info("Generated answer for: %.60s…", query)
    return answer


def stream_answer(
    query: str,
    retrieved_docs: list[Document],
    chat_history: list[dict],
):
    """Yield answer tokens for streaming display.

    Usage with Streamlit:
        answer = st.write_stream(
            stream_answer(query, docs, history)
        )

    Args:
        query: The user's question.
        retrieved_docs: Documents returned by the retriever.
        chat_history: Previous conversation turns.

    Yields:
        String tokens as they are generated by the LLM.
    """
    chain = _build_chain()
    logger.info("Streaming answer for: %.60s…", query)

    yield from chain.stream(
        {
            "context": format_context(retrieved_docs),
            "question": query,
            "chat_history": format_chat_history(chat_history),
        }
    )
